version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "8081:80"

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vulndb
      MYSQL_USER: vulnuser
      MYSQL_PASSWORD: vulnpass
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"
